spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: "http://localhost/api"
          predicates:
            - Path=/**
          filters:
            -AddRequestHeader=X-G_HEADER, red

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8112/eureka/